### ISSUE TITLE
Could not build aragnodb docker image,  getting below error

### ISSUE THREAD

**Issue by bvenkatr** [arangodb/arangodb-docker#10]
![screen shot 2015-07-21 at 7 52 14 pm](https://cloud.githubusercontent.com/assets/6078345/8803134/bfae08ae-2fe2-11e5-887d-b74e65cb1077.png)

I am new to this, Should I install libgoogle-perftools4 on mac?  Any help would be appreciated.  

 OS: Mac Yosemite 10.10.4

**Comment by dothebart** [comment]
Yes, the docker should install this. Which way did you start the installation?

**Comment by bvenkatr** [comment]
I installed Boot2Docker-1.7.0.pkg, and it comes docker tool. Today I tried to build arangodb image like below 
git clone https://github.com/arangodb/arangodb-docker.git
cd arangodb-docker/
docker build -t arangodb .

**Comment by dothebart** [comment]
fixed by #bb1658b9e85f59dea992b57a4d71a6d96cc7793a - please run git pull once.

**Comment by bvenkatr** [comment]
Done,  Thank you very much.
