### ISSUE TITLE
Docker image 3.8.6 ARANGO_ROOT_PASSWORD

### ISSUE THREAD

**Issue by beneiltis** [arangodb/arangodb-docker#106]
Hey folks,

awesome product you have there.
When I try the docker image in version 3.8.6 and set up the env var ARANGO_ROOT_PASSWORD it will not be applied.
If I use version 3.9.0 everything works as expected :-)

Cheers from Cologne
Bene

Keep up the great work!

**Comment by dothebart** [comment]
Hi, 
setting the password only works on a fresh database; can you please add the full comandline of both attempts?

**Comment by beneiltis** [comment]
hi Wilfried, yeah this is what I was expecting. We always create fresh persistent volumes/claims within kubernetes. So it should always be a fresh database.
Sorry I cannot provide you with the full commandline of both attempts.

Feel free to close this if you cannot reproduce.

Have a good one :-)

**Comment by dothebart** [comment]
do you use the kubernetes operator?
Since all of the scripts are identical, I don't see a way how else this could have broken. So without a more detailed description how to reproduce I can't help it.

Greetings from Bergisch Gladbach ;)
