### ISSUE TITLE
ArangoDB 3.10?

### ISSUE THREAD

**Issue by nykma** [arangodb/arangodb-docker#107]
Since [ArangoDB 3.10](https://www.arangodb.com/docs/devel/release-notes-new-features310.html) is out, do we have a plan to update this official docker image?

**Comment by dothebart** [comment]
I'm sorry that the documentation currently creates this erroneous belief - 3.10 has not yet been released. The Documentation hopefully will soon be fixed to properly represent the release state of 3.10.
Please follow https://groups.google.com/g/arangodb-announce for actual release anouncemnets.

**Comment by Simran-B** [comment]
There is no consensus about what the version label should be at the current stage of the release cycle, but there will be a warning on every page of unreleased versions to state that the docs are work in progress. I'm not sure when the docs will be published next but likely soon.
