### ISSUE TITLE
Vulnerabilities with image on DockerHub

### ISSUE THREAD

**Issue by ZimboQC** [arangodb/arangodb-docker#113]
Hi,
Images on Dockerhub contains critical and high vulnerabilites, is it possible to fix them?
<img width="1224" alt="image" src="https://github.com/arangodb/arangodb-docker/assets/37353391/6d8f9801-4d59-45e2-b449-030e55dd9d3a">

**Comment by dothebart** [comment]
hi, 
can we close this as a duplicate of  https://github.com/arangodb/arangodb/issues/19102 ? or are there more?

**Comment by ZimboQC** [comment]
duplicate of https://github.com/arangodb/arangodb/issues/19102
