### ISSUE TITLE
ArangoDB 3.12 or 3.12.1 pulled from dockerhub not working

### ISSUE THREAD

**Issue by scott45** [arangodb/arangodb-docker#118]
Database initialisation script for the databases are, for a reason we are yet to discover, no longer compatible with the ArangoDB `3.12` or `3.12.1` images as distributed from the official ArangoDB page on Docker Hub.

Image tag `3.11.10.1` works very well

**Comment by dothebart** [comment]
Hi, 
can you post your commandline for reference? Do you derive the container?

**Comment by dothebart** [comment]
Hi, any further information? or can we close this?

**Comment by scott45** [comment]
Hi @dothebart I'm going to share more information please. Don't close the issue

**Comment by dothebart** [comment]
Hi, any news?
