### ISSUE TITLE
centos7,cat: can't open '/tmp/init-log': No such file or directory

### ISSUE THREAD

**Issue by paozao** [arangodb/arangodb-docker#119]
i just run 
docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 -d --name arangodb-instance arangodb
then the log error 

Initializing root user...Hang on...
Illegal instruction (core dumped)
Initializing database...Hang on...
ArangoDB didn't start correctly during init
cat: can't open '/tmp/init-log': No such file or directory

my server is x86

**Comment by dothebart** [comment]
Hi, 
please note that you need an AVX2 enabled CPU. This may not be available if you run a VM and did not enable it, or on ARM Mac machines and the Rosetta X86 emulation is used. 

See this issue: https://github.com/arangodb/arangodb/issues/16519

**Comment by paozao** [comment]
thanks ,the arangodb/arangodb:3.9.12-noavx is used。

i have an other question :
How to use the latest compile to -noavx ?

**Comment by paozao** [comment]
thanks ,the arangodb/arangodb:3.9.12-noavx is used。

i have an other question :
How to use the latest compile to -noavx ?

**Comment by dothebart** [comment]
Hi, 
we no longer offer newer noavx builds. For Macs you meanwhile can use native ARM binaries, machines without AVX2 are older than 10 years meanwhile.
