### ISSUE TITLE
host directories, data container - volume access permission denied 

### ISSUE THREAD

**Issue by pmario** [arangodb/arangodb-docker#2]
I'm using boot2docker. Default user there is: docker ... UID:1000   GID:50

arangodb is set to UID:999 GID:999  ... so your "Using host directories" and "Using a data container" examples don't work. They don't start without any error message. 

IMO the info for:  "Using host directories" should be like this:

```
unix> mkdir /tmp/arangodb
unix> sudo chown 999 /tmp/arangodb
unix> docker run -p 8529:8529 -d -v /tmp/arangodb:/data arangodb
```

---

IMO the info for:  "Using a data container" should be like this:

```
unix> docker run -d --name arangodb-persist -v /data -v /apps  ubuntu:14.04 chown 999 /data /apps
unix> docker run --volumes-from arangodb-persist -p 8529:8529 arangodb
```

I personally would use `tianon/true` or `progrium/busybox` to create the volume containers, because of size.

**Comment by pekeler** [comment]
@pmario did you get host directories working with boot2docker? Even with your chmod I'm getting
```
INFO ArangoDB 2.4.1 64bit -- ICU 52.1, V8 3.29.59, OpenSSL 1.0.1f 6 Jan 2014
INFO using default language 'en'
FATAL unable to start WAL logfile manager
More error details may be provided in the logfile '/logs/arangodb.log'
INFO WAL directory '/data/journals' does not exist. creating it...
ERROR could not create WAL directory: '/data/journals': csv is corrupt
ERROR could not create WAL logfile inventory: csv is corrupt
FATAL unable to start WAL logfile manager
```

**Comment by pmario** [comment]
@pekeler With boot2docker, imo you can't use the host directories, since they are not persistent. I use a setup with shared volumes. 

I haven't seen an error message like yours. sry.

**Comment by fceller** [comment]
I think the problem with boot2docker is, that it creates a Linux virtual box on the Mac. So the host is not the Mac but this virtual box,

**Comment by pekeler** [comment]
boot2docker automatically mounts the user's home directory from the mac into the VM. Unfortunately, it seems that permissions are often getting in the way. https://github.com/boot2docker/boot2docker/issues/581

**Comment by gidaltilopes** [comment]
"unix> sudo chown 999 /tmp/arangodb" Worked to me!
thx
