### ISSUE TITLE
File Permissions (2.8.4)

### ISSUE THREAD

**Issue by blindsteal** [arangodb/arangodb-docker#20]
When running with `sudo docker run -e ARANGO_RANDOM_ROOT_PASSWORD=1 --name arango -d -p 80:8529 -v ${PWD}/db:/var/lib/arangodb -v ${PWD}/foxx:/var/lib/arangodb-apps arangodb:2.8.4` on CentOS 7 I get some sed-related error:

``` bash
[pgue@svrsoleng arango]$ sudo docker logs -f arango
Initializing database...Hang on...
===========================================
GENERATED ROOT PASSWORD: M4UEWuHAXGy6qBYn
===========================================
sed: couldn't open temporary file /etc/arangodb/sedqrNrYj: Permission denied
```

Strange thing is, `/etc/arangodb` is not even a volume but on the container fs... I don't really get it, since from reading the Dockerfile I understand it runs as the arangodb user only _after_ applying sed to the config, so before it should be using root (and have correct permissions for `/etc/arango`). Host volume permissions have been set with `chmod 0777` / `chown 999:999`.

Also even when crashing it initializes the database, so starting the container again all goes well and it boots up (but with authorization disabled-- probably due to sed not having applied the config changes).

Am I overlooking something or is it bugged? Thanks in advance, having an officially maintained docker image is a great thing for a database.

**Comment by m0ppers** [comment]
no you are not overlooking something. it is simply broken :| sorry for that. Could you recheck with arangodb/arangodb:2.8.4?

2.8.5 is currently on its way. Once it is released it should contain the fix as well.

**Comment by blindsteal** [comment]
Actually I was using `arangodb:2.8.4` tag already :/ 
This is sad news, do you know what the reason for this error is? I suspected it was only some mistake in your Dockerfile that's easy to fix (or work around), if you can steer me in the right direction I might even submit a PR...

**Comment by m0ppers** [comment]
notice that I am speaking of the non official arangodb/arangodb:2.8.4 (as opposed to arangodb:2.8.4) image. The bug is inside the entrypoint. check my commit here:

https://github.com/arangodb/arangodb-docker/commit/4a154ab2f994eefc75531436141f00bf657a1e91

**Comment by blindsteal** [comment]
Alright so there is another image and you fixed it already... Nice! `arangodb/arangodb:2.8.4` gets the job done :)

**Comment by m0ppers** [comment]
It is basically the same image - just a different namespace/owner. The official is maintained by the docker library guys and arangodb/arangodb is ours (while using the same Dockerfile). So I could easily update the existing one in our repo ;) no idea how to update the official one but as 2.8.5 is on its way I think there is no need for immediate action in the official repo :) Glad it works!
