### ISSUE TITLE
using on windows with volume definition

### ISSUE THREAD

**Issue by maku** [arangodb/arangodb-docker#24]
I would like to use arangodb-docker on an Win7-64 machine. e.g. with the following command

docker -e ARANGO_NO_AUTH=1 run -p 8529:8529 -v /DB/arangodb:/var/lib/arangodb arangodb

But I get the following error:

`We seem to not have proper rw access to /var/lib/arangodb. Please make sure that every mounted volume has full rw access for user arangodb (uid=999(arangodb) gid=999(arangodb) groups=999(arangodb))`

Is there a way how to handle this error?

**Comment by dothebart** [comment]
have a look at: https://docs.arangodb.com/cookbook/Cloud/DockerContainer.html#persistent-data
