### ISSUE TITLE
Docker build of Arango 3.1.7 don't provide graph preview toolbars (left and top)

### ISSUE THREAD

**Issue by lucklo** [arangodb/arangodb-docker#27]
Using docker builds of arango 3.1 left and top bar utitlities are missing. 
See [http://i.imgur.com/g3JlN96.png](http://i.imgur.com/g3JlN96.png)

Installed both 3.1.1 and 3.1.7 (latest) with same effect using:
`docker run --name arangodb311 -p 8529:8529 -e ARANGO_ROOT_PASSWORD=root arangodb/arangodb:3.1.1`

Graph modeling UI is significantly different in 3.1.* builds. 
Documentation doesn't include any mention of this new UI and details os it's usage.

When installed any version of 3.0 tree I was able to see and use all toolbars as visible in [Docs](https://docs.arangodb.com/3.1/Manual/Administration/WebInterface/images/graphViewer.png)

In both cases I used Social Graph Example using fresh build.
Host OS is MacOS X 10.12.1.

**Comment by dothebart** [comment]
One of the big new features in 3.1 is the new graph viewer which presumably scales better to graphs with more nodes. 
However, as you found out we forgot to add to document it! 
The new graph viewers options pane can be opened in the upper right when clicking on the icon with the 3 vertical bars.

@hkernbach will fix the documentation.

**Comment by weinberger** [comment]
@lucklo My mistake. I have 3.0 installed. If you choose canvas then you have similar functionality if you make a right click on a vertex. Sorry for that.

**Comment by hkernbach** [comment]
Thanks. Documentation is now updated (source code - https://github.com/arangodb/arangodb/commit/157c2067655d61b36edfa2700354aee1bb334545). This will be also updated @ https://docs.arangodb.com/devel/Manual/ in a few days and also in the official documentation when a new bugfix release will be available.

**Comment by dothebart** [comment]
@lucklo https://docs.arangodb.com/devel/Manual/Administration/WebInterface/Graphs.html has been updated and now shows @hkernbach edits.

**Comment by lucklo** [comment]
@dothebart @weinberger @hkernbach Thank you, it looks great!
Are there any plans for some Video Tutorials for this new UI - that would be awesome addition for beginners!
