### ISSUE TITLE
How to Run ArangoDB Container on Openshift Container Platform

### ISSUE THREAD

**Issue by farshadahmadi** [arangodb/arangodb-docker#34]
I am trying to run the ArangoDB container on Openshift platform. It throws the following error:

`chown: changing ownership of '/var/lib/arangodb3': Operation not permitted`

I know it is not your problem and Openshift guys should provide it, but have you guys thought about providing a container that can also run on Openshift platform?

FYI. I also wrote about this request on stackoverflow (https://stackoverflow.com/questions/44756008/how-to-run-arangodb-on-openshift)

**Comment by dothebart** [comment]
As you found https://github.com/openshift/origin/issues/6282 it seems its currently not supported. 

In doubt you can try to start your own dockerfile, remove all that chown etc. logic, and run the arangod as root. But I don't see any way how we could support you here.

**Comment by dothebart** [comment]
Hi, 
as upstream doesn't seem to care about this issue I can't help but close this now. 
If you get upstream to care about this issue, feel free to comment / reopen.
