### ISSUE TITLE
RocksDB Host Directory folder appears with mmfiles engine

### ISSUE THREAD

**Issue by davidmw** [arangodb/arangodb-docker#36]
After starting arangodb from the docker image, with a host directory configured on the command line (directory did not exist), and confirming that Community Edition is running with mmfiles as the engine (Web Interface) - this is the contents of my host directory on OSX:

![screen shot 2017-09-14 at 11 22 05 am](https://user-images.githubusercontent.com/3413901/30408051-bcbeb346-993f-11e7-81c4-28701a053bdb.png)

It probably is nothing other than a nuisance but did result in some wasted time and some restarts. So far deleting the RocksDB folder doesn't seem to impact anything.

David

**Comment by dothebart** [comment]
The MMFiles engine has an index type called [`persistent index`](https://docs.arangodb.com/3.2/Manual/Indexing/Persistent.html) which is implemented on top of rocksdb. So unless you create such an index, this database will remain empty, but is still required.

**Comment by davidmw** [comment]
Thanks much.
