### ISSUE TITLE
docker image couldn't run entrypoint.sh 

### ISSUE THREAD

**Issue by weiklr** [arangodb/arangodb-docker#42]
Hi,

i tried to build a arangodb image using dockefile33.local and couldn't run the image after building it.

I realize you need to update the execution rights to make it work in the dockerfile after copying the entrypoint.sh with: chmod +x /entrypoint.sh

**Comment by dothebart** [comment]
Hi, 
the file has an execute flag inside of the git repo; which is why this is "works for me" ;-)

Do you use a host that can't provide these flags?

**Comment by weiklr** [comment]
hi, you are right. I downloaded the file manually and didn't do a git clone. perhaps that's why the file doesn't have the execute flag

**Comment by dothebart** [comment]
Ok, I'd like to close this then.
