### ISSUE TITLE
Error when starting container with rocksdb 

### ISSUE THREAD

**Issue by haseebnaseem** [arangodb/arangodb-docker#44]
Environment: Kubernetes
Running as a cluster, the following error is thrown and the container fails to start.
`FATAL {startup} unable to initialize RocksDB engine: IO error: No space left on device/var/lib/arangodb3/engine-rocksdb/000304.sst: No space left on device; Maybe your filesystem doesn't provide required features? (Cifs? NFS?)`

**Comment by dothebart** [comment]
meanwhile arangodb on kubernetes is supported via  https://github.com/arangodb/kube-arangodb - closing this issue.
