### ISSUE TITLE
Port customization does not work.

### ISSUE THREAD

**Issue by nkanand4** [arangodb/arangodb-docker#45]
Trying to customize Arango instance port to something other than 8529 does not work.
<img width="1306" alt="screen shot 2018-02-25 at 10 55 21 pm" src="https://user-images.githubusercontent.com/667996/36654105-d8458e66-1a7f-11e8-8a20-f232979d48fc.png">

**Comment by dothebart** [comment]
Hi, 
you can modify the bind port inside the container via environment variables. please have a look at https://hub.docker.com/_/arangodb/

`-p` only creates a portforward from inside of the docker container to the outside world. 
You can however use this to map the default port `8529` to `8888` like this: `-p 8529:8888`

**Comment by nkanand4** [comment]
I was able to use the --server.endpoint option to customize it to use a different port. However, I noticed that it is accessible from within the container but not outside. Not sure what is interfering now. Help is much appreciated. <img width="1419" alt="screen shot 2018-02-26 at 10 07 11 am" src="https://user-images.githubusercontent.com/667996/36681529-79659b84-1ade-11e8-9eba-1047884cfed7.png">

**Comment by dothebart** [comment]
I can only repeat myself - you [have to forward the port into the docker container via the docker commandline arguments](https://stackoverflow.com/questions/32070789/portforwarding-from-within-docker-container)

**Comment by nkanand4** [comment]
I think you might have missed to note that from my later screenshot that I have done that already. I have customized it to run on a different port. That's how I am able to curl from within container. Also exposed that port and done the binding. Please note that in screenshot.

**Comment by dothebart** [comment]
Sometimes docker fails to set the firewall routing rules for containers. Restarting Firewalls and docker deamon and in doubt the full system usually fixes that. 
Please don't use screenshots, cut'n'paste doesn't work with these. Use tripple-backticks instead to blockquote cut'n'paste content.

**Comment by nkanand4** [comment]
This totally makes sense. Let me give it a try and I will update this post. Thanks.
