### ISSUE TITLE
Data Directory Wrong on Dockerhub

### ISSUE THREAD

**Issue by chainlink** [arangodb/arangodb-docker#46]
The Data Directory on `3.3.3` has been changed to `/var/lib/arangodb3` from `/var/lib/arangodb` as specified in all the docs on dockerhub. Where can I file a PR to update this?

ref: https://hub.docker.com/r/arangodb/arangodb/

**Comment by dothebart** [comment]
oh, this has been changed with arangodb 3.0 - so we need to update that documentation asap.

**Comment by dothebart** [comment]
ok, in fact we need to re-sync it with https://hub.docker.com/_/arangodb/

**Comment by dothebart** [comment]
done, thanks for reporting.

**Comment by chainlink** [comment]
Thanks for the quick response! Curious as to why there is `/arango` and `arango/arango` on dockerhub?

**Comment by dothebart** [comment]
Hi, 
both are maintained via our release process. 
However, the `_` version is the official docker library version, which requires upstream to accept a pull request. 

Historically the arangodb/arangodb version was there first, so we kept it around.
