### ISSUE TITLE
Failed to build local version of container for testing

### ISSUE THREAD

**Issue by gbjbaaha** [arangodb/arangodb-docker#49]
Hi,
I've hit the same issue as report in https://github.com/arangodb/arangodb-docker/issues/48, but also seems to be an issue when running under Docker Swarm. To try and investigate, I tried downloading this project and following the instructions for "Building your own ArangoDB image".

I want to build a container for ArangoDB 3.3.11 but the contents of DockerFile.templ appear to be pointing at an ArangoDB version 2 download binary.

Please advise as I believe the documentation may be out of date.

Thanks
Andrew

**Comment by dothebart** [comment]
Hi, 
the .templ files are there to generate docker library templates - like https://github.com/arangodb/arangodb-docker/tree/official/stretch/3.2.15 via the release scripts; you can't use them directly. 

i.e. https://github.com/arangodb/arangodb-docker/blob/official/Dockerfile33.local can be used to create a docker container using an `arangodb.deb` package in the very same directory - which is probably what you want.

**Comment by gbjbaaha** [comment]
Hi. Err OK, but the documentation in the main README file states:-

```
We are auto generating docker images via our build system so the Dockerfile is a template. To build your own ArangoDB image:

cp Dockerfile.templ Dockerfile

Adjust @VERSION@ in the Dockerfile to the version of arangodb you want to have and issue:

docker build -t arangodb .

This will create an image named arangodb.
```

Does the README need updating to clarify what is needed to build your own container image?

Thanks
Andrew
