### ISSUE TITLE
arangodb/arangodb:latest changed from debian to alpine?

### ISSUE THREAD

**Issue by stumo** [arangodb/arangodb-docker#59]
I'm seeing issues which suggest the base image for arangodb/arangodb:latest has changed from debian (with apt-get) to alpine (with apk) - is this an intentional, long term change?

**Comment by dothebart** [comment]
Yes - exactly, ArangoDB3.4 now comes as an alpine image.

**Comment by dothebart** [comment]
see https://www.arangodb.com/2018/12/arangodb-3-4-full-text-search-geojson/ for the whole glory ;-)

**Comment by fceller** [comment]
@stumo alpine has a lot fewer security issues - as the image itself contains only the bare minimum software packages. Therefore we switched to Alpine.

As a side effect, the image is a bit smaller. But the main reason is security.

**Comment by stumo** [comment]
Thanks. No problems with the change, just wanted to check it was long term before I started updating scripts
