### ISSUE TITLE
Coordinator container crashing 

### ISSUE THREAD

**Issue by haseebnaseem** [arangodb/arangodb-docker#60]
We have an arangodb cluster deployed using kubernetes. One of the coordinator container is crashing upon startup with only the following logs:
`automatically choosing storage engine
{startup} obsolete option '--cluster.my-local-info' used in configuration. setting this option will not have any effect.`

**Comment by dothebart** [comment]
Please open the issue on the arangodb main repository. 
Can you ensure your system supports SSE 4.2 ?
