### ISSUE TITLE
Document how to run the ArangoDB container in read-only mode

### ISSUE THREAD

**Issue by ixxie** [arangodb/arangodb-docker#61]
It is a general security recommendation to run containers in `read_only` mode except for the volumes you need to use. On `arangodb:3.3` we could simply mount `/var/lib/arangodb3` to a data volume, and set `tmpfs` to the host's `/tmp` directory. 

It seems that with `arangodb:3.4` the foxx-cli are run as root and try to write a `.foxxrc` file to `/root/.foxxrc` and failing. The log shows:

    Error: EROFS: read-only file system, open '/root/.foxxrc'

*Side-note:* the way the `entrypoint.sh` script loads initialization scripts, and specifically *when* it does so, isn't very clearly documented (we read through the script to figure this out). Since this is very valuable (seems to be one of the best ways to initialize ArangoDB) a little documentation would go a long way!

**Comment by fceller** [comment]
moved .foxxrc to /tmp
