### ISSUE TITLE
3.4.0 images should default to `log.output` of `-` (stdout)

### ISSUE THREAD

**Issue by rocketraman** [arangodb/arangodb-docker#62]
I upgraded my cluster from 3.3.x to 3.4.1 I actually thought the upgrade failed (see https://github.com/arangodb/arangodb/issues/7914) because the default log output of a 3.4.1 cluster goes to a file (see `/etc/arangodb/arang`). The echo messages from the init script do show up on stdout, so if one is looking at the container logs, it *seems* like the server has just hung, when in fact it is likely starting normally.

I do see https://github.com/arangodb/arangodb-docker/blob/c77fa2b9bca45deb37e2a709dead1147541857ba/alpine/3.4.1/Dockerfile#L30 is intended to set the output to standard output but as you can see, it does not appear to be working:

```
$ kubectl exec -it arangodb-db-0 --namespace default grep "file =" /tmp/arangod.conf
file = /var/log/arangodb3/arangod.log
```

**Comment by jan-zajic** [comment]
Temporary fix is to start container with CMD: "--log.output -".

**Comment by dothebart** [comment]
Note: the `_/arangodb` container shouldn't be doing this, only the `arangodb/arangodb` one.

**Comment by fceller** [comment]
fixed Dockerfile in oskar
