### ISSUE TITLE
Template file for v3.5?

### ISSUE THREAD

**Issue by ex-nerd** [arangodb/arangodb-docker#73]
v3.5 is out now.  It would be nice if there were templates/images to go with it.

**Comment by dothebart** [comment]
https://github.com/arangodb/arangodb-docker/tree/official/alpine/3.5.0 ?

**Comment by ex-nerd** [comment]
I guess I was referring to the `.template` files at the root level of the repo.  But then I did notice that there are images available, which is actually all that I was looking for.

**Comment by dothebart** [comment]
these template files are used to be specialized for the respective releases. So I will close this now.
