### ISSUE TITLE
Documentation about default username and password

### ISSUE THREAD

**Issue by kevinprotoss** [arangodb/arangodb-docker#8]
Hi, 

after 2.6.0, I found arangodb has a default username and password after container run. There is no documentation about that in any arangodb repositories. In the end, after docker logs, I found the root user and auto generated password in the console.
I think it's not pretty clear to users. The better the documentation should be improved about that later.

Best regards,
Kevin

**Comment by fceller** [comment]
It is documented in the 2.6 branch - but missing in master. Need to merge.

**Comment by kevinprotoss** [comment]
Ah, I see.

Thanks

**Comment by kevinprotoss** [comment]
By the way, is there any options for docker run command line so as to disable authentication?

**Comment by fceller** [comment]
> docker run -P arangodb/arangodb:2.6.0 help
volumes:
  /data    	database files
  /apps    	application directory
  /apps-dev	application directory for development
  /logs    	log directory

pipe the log file to standard out:
  docker run arangodb standalone --verbose

disable authentication
  docker run arangodb standalone --disable-authentication

fire up a bash after starting the server:
  docker run -it arangodb standalone --console

show all options:
  docker run arangodb help

**Comment by kevinprotoss** [comment]
Super, my app works again now. Thx for your answer.
