### ISSUE TITLE
Arangodb 3.6.2 image

### ISSUE THREAD

**Issue by 153957** [arangodb/arangodb-docker#85]
Please provide a docker image for Arangodb 3.6.2.

Would it help to make a PR for this, or should we just wait a bit?

@KVS85

**Comment by dothebart** [comment]
It is not released yet. Please follow the regular release channels where we anounce this - i.e. 
https://groups.google.com/forum/#!forum/arangodb-announce

**Comment by KVS85** [comment]
@153957 please, wait a little bit. We plan to release 3.6.2 very soon. Meanwhile you can use preview images:
- https://hub.docker.com/layers/arangodb/arangodb-preview/3.6.2/images/sha256-cf9f41636d1022425f0d2e31c2796c808cf3e72436099e0918fe5c284dbdf041
- https://hub.docker.com/layers/arangodb/enterprise-preview/3.6.2/images/sha256-b3d53bda214f9f797061fd74327b08cf41ee36cb9334eef95a4ad41151ff5e27

**Comment by 153957** [comment]
Ah my mistake! I was following the GitHub releases page: https://github.com/arangodb/arangodb/releases

Thanks for directing me to the correct place.

**Comment by dothebart** [comment]
These probably only list release tags - which are created before the QA is done ;)
