### ISSUE TITLE
3.7.3 and release schedules

### ISSUE THREAD

**Issue by curtdept** [arangodb/arangodb-docker#92]
So I stop asking and being irritating, is the delay between arango releases and docker updates intentional?

I am happy to PR these or do some work to keep this up to date if you want.

Thanks for the help 👍 
-Curtis

**Comment by dothebart** [comment]
Hi, 
the release process looks as the following: 

- set the tag
- build binaries
- run QA on them
- decide on publification date (maybe marketing wants to do something...) 
- once its like that, publish; create PR to the docker library for `_/arangodb`, upload docker container to `arangodb/arangodb`
- create PR for homebrew (if newes release)

There may be internal releases that are not shared; you will not find them on the regular download pages, i.e. if we see that we need an urgent fix for Oasis or another enterprise customer that shouldn't wait for the regular release process. 

However, if a release is published to the broader public, the PR to the docker library is created, and will be applied some hours later.
So there is no need to create an own PR.

**Comment by curtdept** [comment]
Ok sounds good thank you 👍
