### ISSUE TITLE
docker image usable for raspi (ubuntu)

### ISSUE THREAD

**Issue by maku** [arangodb/arangodb-docker#95]
I have an raspi 4 which runs ubuntu ( Ubuntu 20.04 LTS (GNU/Linux 5.4.0-1025-raspi aarch64)) and would like to use arangodb with docker.

Is there an image out which is usable in this context (without compiling myself)?

**Comment by dothebart** [comment]
Hi, 
Please have a look at: 
https://github.com/arangodb/arangodb-docker/issues/53
there is an ongoing discussion; however, there are currently only older experimental images available.

**Comment by maku** [comment]
@dothebart thank you, I know this issue. But it is not really that useful... I learn that it is not (easy) possible ...
