### ISSUE TITLE
[Question] Enter docker container

### ISSUE THREAD

**Issue by Minstel** [arangodb/arangodb-docker#97]
I want to enter running arango docker container. Tryed the following standard command:

```
sudo docker exec -it graphdb bash
```

But received the response:

```
OCI runtime exec failed: exec failed: container_linux.go:367: starting container process caused: exec: "bash": executable file not found in $PATH: unknown
```

The same is using `/bin/bash`.
The only option I found working is using `arangosh` as command, but that is not really what I want to do, as it enters arango shell, not container's filesystem.

So is there a way to do this?

**Comment by dbenesj** [comment]
Sure, just use `sh` instead of `bash`

**Comment by dothebart** [comment]
exactly. to reduce the container size arangodb comes with only /bin/sh instead of a full blown bash. Its also based on alpine, so if you need the compfort of a bash, please follow i.e. https://www.cyberciti.biz/faq/alpine-linux-install-bash-using-apk-command/

**Comment by Minstel** [comment]
Great, thanks a lot!
